### ISSUE TITLE
Solbero's Kodi add-on repository empty?

### ISSUE THREAD

**Issue by jacobhallberg98** [solbero/guide-kodi-lutris#8]
I am trying to install the Kodi add-on repository, I downloaded the zip file as per the instructions but when I try to go into the "Program add ons" inside the solbero Kodi add-on repository there's nothing there. Help!

![2021-08-04-155032_1920x1080_scrot](https://user-images.githubusercontent.com/69006684/128193272-ed8dc536-a151-44ce-8c74-b31f28fe1325.png)

**Comment by solbero** [comment]
That is a strange behaviour. But it is to be expected since the guide is a bit outdated, but I am in the process of rewriting it.

Try installing [this repository](https://github.com/solbero/repository.solbero.matrix/raw/master/repository.solbero.matrix/repository.solbero.matrix.zip) instead which has a version of the add-on for Kodi v19 Matrix.

**Comment by solbero** [comment]
I have also updated the URL to the repository in the guide. It should now be correct.

**Comment by jacobhallberg98** [comment]
That updated URL worked, thanks!
